spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/auth_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: secret-key
  expirationSec: 3600 # 60 * 60 = 1hour
  expirationRedisSec: 1209600 # 60 * 60 * 24 * 14
